# Site settings
title: Bigolaro
email: bigolaro@xavieralexandre.io
description: "Nouvelles et ressources du projet Bigolaro."
baseurl: "/bigolaro"
url: "http://www.bigolaro.ch"

# Build settings
markdown: kramdown
permalink: pretty
