# Site settings
title: Bigolaro
email: cuocoli@gmail.com
description: "Nouvelles et ressources du projet Bigolaro."
baseurl: "/bigolaro"
url: "http://xavieralexandre.org/bigolaro"

# Build settings
markdown: kramdown
permalink: pretty
  
collections:
 recettes:
  output: true
  permalink: /recettes/
